// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	SessionID string `json:"sessionId" bson:"sessionId"`
	Author    string `json:"author" bson:"author"`
	Contents  string `json:"contents" bson:"contents"`
}

type GameSession struct {
	ID           string     `json:"_id" bson:"_id"`
	Name         string     `json:"name" bson:"name"`
	Ongoing      bool       `json:"ongoing" bson:"ongoing"`
	Participants []string   `json:"participants" bson:"participants"`
	Comments     []*Comment `json:"comments" bson:"comments"`
}

type NewComment struct {
	SessionID string `json:"sessionId" bson:"sessionId"`
	Author    string `json:"author" bson:"author"`
	Contents  string `json:"contents" bson:"contents"`
}

type NewGameSession struct {
	Name      string `json:"name" bson:"name"`
	Initiator string `json:"initiator" bson:"initiator"`
}

type NewParticipant struct {
	SessionID string `json:"sessionId" bson:"sessionId"`
	UserID    string `json:"userId" bson:"userId"`
}
